Fix bugs in NuE/NueScatterGen_module.cc
DUNE/dunesim pull request #50
Opened 2023-10-30 22:39 UTC by tomjunk

The random sampling in TF1::GetRandom was hanging.  Turns out setting Npx helps.  See 

https://root-forum.cern.ch/t/problem-generating-a-distribution-using-tf1-getrandom-function/44812

for a discussion.  Instead of computing Npx, it is just a fcl parameter.

I also deleted the old version in NuEScattering -- it wasn't being built anyway and had the same name as the active code.

I also set fFlatESpectrum from the fcl parameter -- was forgotten before.

2023-10-31 09:09 UTC, absolution1 reviewed
Hi Tom.
Thanks for adding these.
I added a single comment about the default values when reading in the FCL pset.

Cheers!

2023-10-31 09:09 UTC, absolution1 commented on dunesim/EventGenerator/NuE/NuEScatterGen_module.cc
> +    fNpxNutaubarE      = p.get<int>("fNpxNutaubarE",1500);
The default values could be dropped as they could end up being a point of user error (e.g. if someone typos the name of the variable in their own fcl)

2023-10-31 23:38 UTC, mhlswang commented
Hi Tom, I tried running it and found the following minor typos in the lines that Dom referred to above:
the "f" in the  "fNpxNu*" in p.get<int>("fNpxNu*",1500) needs to be removed.  Other than this, everything looks ok.

2023-10-31 23:49 UTC, mhlswang requested changes
Hi Tom, I tried running it and found the following minor typos in the lines that Dom referred to above:
the `f` in the `fNpxNu*` in `p.get<int>("fNpxNu*")` needs to be removed. Other than this, everything looks ok.

2023-11-01 20:44 UTC, tomjunk commented
Thanks!  I just pushed a commit that hopefully addresses both of these comments.

2023-11-02 07:48 UTC, absolution1 approved these changes
Thanks for making the change @tomjunk 
This looks good to me!

2023-11-03 19:17 UTC, merged